ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include("paypal.standard.ipn.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('',views.index,name='index'),
    path('categoria/<int:categoria_id>',views.productos_por_categoria,name='categoria'),
    path('marca/<int:marca_id>',views.productos_por_marca,name='marca'),
    path('busqueda',views.producto_por_nombre,name='busqueda'),
    path('producto/<int:producto_id>',views.producto_detalle,name='producto'),
    path('cart',views.carrito,name='carrito'),
    path('cart/add/<int:producto_id>',views.agregar_carrito,name='cart_add'),
    path('cart/del/<int:producto_id>',views.eliminar_producto_carrito,name='cart_del'),
    path('cart/clear',views.limpiar_carrito,name='cart_clear'),
    path('auth/register',views.crear_usuario,name='auth_register'),
    path('cuenta',views.cuenta_usuario,name='cuenta'),
    path('auth/login',views.login_usuario,name='auth_login'),
    path('auth/logout',views.logout_usuario,name='auth_logout'),
    path('cliente/act',views.actualizar_cliente,name='cliente_act'),
    path('pedido',views.pedido,name='pedido'),
    path('pedido/add',views.registrar_pedido,name='pedido_add'),
    path('pago',views.registro_pago,name='pago')
]

web/templates/includes/footer.html
<div class="container-fluid blog-sb-widgets page-styling site-footer">
    <div class="row">
        <div class="col-sm-12 col-md-4 widget align-center-tablet f-logo-wrap">
            <a href="index.html" class="f-logo">
                <img src="img/logo.png" alt="">
            </a>
            <p>Modern eCommerce HTML Template</p>
            <button class="btn callback">Contact Us</button>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Company</h3>
            <ul class="menu">
                <li>
                    <a href="index.html">Front Page</a>
                </li>
                <li>
                    <a href="about.html">About Us</a>
                </li>
                <li>
                    <a href="contacts.html">Contacts</a>
                </li>
                <li>
                    <a href="index.html">Gallery</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Shop</h3>
            <ul class="menu">
                <li>
                    <a href="catalog-list.html">Electricity</a>
                </li>
                <li>
                    <a href="catalog-gallery.html">Fasteners</a>
                </li>
                <li>
                    <a href="catalog-gallery-full.html">Lighting</a>
                </li>
                <li>
                    <a href="catalog-gallery.html">Pipes</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Account</h3>
            <ul class="menu">
                <li>
                    <a href="wishlist.html">Wishlist</a>
                </li>
                <li>
                    <a href="compare.html">Compare</a>
                </li>
                <li>
                    <a href="cart.html">Cart</a>
                </li>
                <li>
                    <a href="auth.html">My Account</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Blog</h3>
            <ul class="menu">
                <li>
                    <a href="blog.html">All Posts</a>
                </li>
                <li>
                    <a href="post.html">News</a>
                </li>
                <li>
                    <a href="post-slider.html">Articles</a>
                </li>
                <li>
                    <a href="blog.html">Reviews</a>
                </li>
            </ul>
        </div>
    </div>
</div>

web/templates/includes/header.html
{% load static %}
<div class="site-header">

    <p class="h-logo">
        <a href="/"><img src="{% static 'img/logo.png' %}" alt="MultiShop"></a>
    </p><!--
No Space
--><div class="h-shop">

    <form method="post" action="/busqueda" class="h-search" id="h-search">
        {% csrf_token %}
        <input type="text" placeholder="busqueda..." name="nombre">
        <button type="submit"><i class="ion-search"></i></button>
    </form>

    <ul class="h-shop-links">
        <li class="h-search-btn" id="h-search-btn"><i class="ion-search"></i></li>
        <li class="h-shop-icon h-wishlist">
            <a title="Wishlist" href="wishlist.html">
                <i class="ion-heart"></i>
                <span>5</span>
            </a>
        </li>
        <li class="h-shop-icon h-compare">
            <a title="Compare List" href="compare.html">
                <i class="ion-arrow-swap"></i>
                <span>2</span>
            </a>
        </li>
        <li class="h-shop-icon h-profile">
            <a href="auth.html" title="My Account">
                <i class="ion-android-person"></i>
            </a>
            <ul class="h-profile-links">
                {% if user.is_authenticated %}           
                    <li><a href="{% url 'web:auth_logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'web:auth_login' %}">Login / Registration</a></li>
                {% endif %}
            </ul>
        </li>

        <li class="h-cart">
            <a class="cart-contents" href="cart.html">
                <p class="h-cart-icon">
                    <i class="ion-android-cart"></i>
                    <span>3</span>
                </p>
                <p class="h-cart-total">$510.00</p>
            </a>
            <div class="widget_shopping_cart">
                <div class="widget_shopping_cart_content">
                    <ul class="cart_list">
                        <li>
                            <a href="#" class="remove">&times;</a>
                            <a href="#">
                                <img src="http://placehold.it/100x67" alt="">
                                Pneumatic Coil Hose
                            </a>
                            <span class="quantity">1 &times; $180.00</span>
                        </li>
                        <li>
                            <a href="#" class="remove">&times;</a>
                            <a href="#">
                                <img src="http://placehold.it/100x89" alt="">
                                Drill Tool Kit
                            </a>
                            <span class="quantity">1 &times; $115.00</span>
                        </li>
                        <li>
                            <a href="#" class="remove">&times;</a>
                            <a href="#">
                                <img src="http://placehold.it/100x89" alt="">
                                Searchlight Portable
                            </a>
                            <span class="quantity">1 &times; $150.00</span>
                        </li>
                    </ul>
                    <p class="total"><b>Subtotal:</b> $510.00</p>
                    <p class="buttons">
                        <a href="/cart" class="button">View cart</a>
                        <a href="checkout.html" class="button">Checkout</a>
                    </p>
                </div>
            </div>
        </li>

        <li class="h-menu-btn" id="h-menu-btn">
            <i class="ion-navicon"></i> Menu
        </li>
    </ul>
</div><!--
No Space
--><div class="mainmenu">

    <nav id="h-menu" class="h-menu">
        <ul>
            <li class="menu-item-has-children">
                <a href="index.html">Home</a>
                <ul class="sub-menu">
                    <li>
                        <a href="index.html">Home 1</a>
                    </li>
                    <li>
                        <a href="index-2.html">Home 2</a>
                    </li>
                </ul>
            </li>
            <li class="menu-item-has-children active">
                <a href="catalog-gallery.html">Shop</a>
                <ul class="sub-menu">
                    <li class="active">
                        <a href="catalog-gallery.html">Catalog - Gallery</a>
                    </li>
                    <li>
                        <a href="catalog-list.html">Catalog - List</a>
                    </li>
                    <li>
                        <a href="catalog-gallery-full.html">Catalog - No Sidebar</a>
                    </li>
                    <li>
                        <a href="product.html">Product Page</a>
                    </li>
                    <li class="menu-item-has-children">
                        <a href="cart.html">Shop Pages</a>
                        <ul class="sub-menu">
                            <li>
                                <a href="cart.html">Cart</a>
                            </li>
                            <li>
                                <a href="wishlist.html">Wishlist</a>
                            </li>
                            <li>
                                <a href="compare.html">Compare</a>
                            </li>
                            <li>
                                <a href="auth.html">Login</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <a href="elements.html">Elements</a>
            </li>
            <li class="menu-item-has-children">
                <a href="blog.html">Blog</a>
                <ul class="sub-menu">
                    <li>
                        <a href="blog.html">Blog Posts</a>
                    </li>
                    <li>
                        <a href="post.html">Standard Post</a>
                    </li>
                    <li>
                        <a href="post-slider.html">Slider Post</a>
                    </li>
                </ul>
            </li>
            <li class="menu-item-has-children">
                <a href="about.html">Pages</a>
                <ul class="sub-menu">
                    <li>
                        <a href="about.html">About Us</a>
                    </li>
                    <li>
                        <a href="contacts.html">Contacts</a>
                    </li>
                    <li>
                        <a href="gallery.html">Gallery</a>
                    </li>
                    <li>
                        <a href="404.html">Error 404</a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>

</div><!--
No Space
--></div>

web/templates/includes/meta.html
{% load static %}
<meta charset="UTF-8">
<title>Ecommerce Codigo G20</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="format-detection" content="telephone=no">

<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900%7COpen+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=cyrillic" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.formstyler.css' %}">
<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">
<link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.mThumbnailScroller.css' %}">
<link rel="stylesheet" href="{% static 'css/chosen.css' %}">

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/elements.css' %}">
<link rel="stylesheet" href="{% static 'css/media.css' %}">
<link rel="stylesheet" href="{% static 'css/elements-media.css' %}">

web/templates/includes/modals.html
<div class="form-validate modal-form" id="modal-form">
    <form action="#" method="POST" class="form-validate">
        <h4>Contact Us</h4>
        <input type="text" placeholder="Your name" data-required="text" name="name">
        <input type="text" placeholder="Your phone" data-required="text" name="phone">
        <input type="text" placeholder="Your email" data-required="text" data-required-email="email" name="email">
        <input class="btn1" type="submit" value="Send">
    </form>
</div>

<div class="cont maincont quick-view-modal">
    <article>
        <div class="prod">
            <div class="prod-slider-wrap prod-slider-shown">
                <div class="flexslider prod-slider" id="prod-slider">
                    <ul class="slides">
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/1000x1000">
                                <img src="http://placehold.it/550x550" alt="">
                            </a>
                        </li>
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/1000x1000">
                                <img src="http://placehold.it/550x550" alt="">
                            </a>
                        </li>
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/1000x1000">
                                <img  src="http://placehold.it/550x550" alt="">
                            </a>
                        </li>
                    </ul>
                    <div class="prod-slider-count"><p><span class="count-cur">1</span> / <span class="count-all">3</span></p><p class="hover-label prod-slider-zoom"><i class="icon ion-search"></i><span>Zoom In</span></p></div>
                </div>
                <div class="flexslider prod-thumbs" id="prod-thumbs">
                    <ul class="slides">
                        <li>
                            <img src="http://placehold.it/550x550" alt="">
                        </li>
                        <li>
                            <img src="http://placehold.it/550x550" alt="">
                        </li>
                        <li>
                            <img src="http://placehold.it/550x550" alt="">
                        </li>
                    </ul>
                </div>
            </div>
            <div class="prod-cont">
                <div class="prod-rating-wrap">
                    <p data-rating="4" class="prod-rating">
                        <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                    </p>
                    <p class="prod-rating-count">7</p>
                </div>
                <p class="prod-categs"><a href="#">Lighting</a>, <a href="#">Tools</a></p>
                <h2>Belt Sanders</h2>
                <p class="prod-price">$25.00</p>
                <p class="stock in-stock">7 in stock</p>
                <p class="prod-excerpt">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget...</p>
                <div class="prod-add">
                    <button type="submit"
                            class="button"><i class="icon ion-android-cart"></i> Add to cart
                    </button>
                    <p class="qnt-wrap prod-li-qnt">
                        <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                        <input type="text" value="1">
                        <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                    </p>
                    <div class="prod-li-favorites">
                        <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                    </div>
                    <p class="prod-li-compare">
                        <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                    </p>
                </div>
            </div>
        </div>
    </article>
</div>

web/templates/includes/navbar.html
<div class="container-fluid page-styling site-header-before">
    <div class="row">
        <div class="col-lg-4">
            <ul class="links_list links_list-align-left align-center-desktop topbar-social">
                <li>
                    <p class="links_list-value">
                        <a href="http://facebook.com" target="_blank" rel="nofollow">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="mailto:email@email.com" target="_blank" rel="nofollow">
                            <i class="fa fa-paper-plane"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://pinterest.com" target="_blank" rel="nofollow">
                            <i class="fa fa-pinterest-p"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://youtube.com" target="_blank" rel="nofollow">
                            <i class="fa fa-youtube-play"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://twitter.com" target="_blank" rel="nofollow">
                            <i class="fa fa-twitter"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://google.com" target="_blank" rel="nofollow">
                            <i class="fa fa-google-plus"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://instagram.com" target="_blank" rel="nofollow">
                            <i class="fa fa-instagram"></i>
                        </a>
                    </p>
                </li>
            </ul>
        </div>
        <div class="col-lg-8">
            <ul class="links_list links_list-align-right align-center-desktop topbar-contacts">
                <li>
                    <p class="links_list-label">
                        Our Address
                    </p>
                    <p class="links_list-value">
                        <a href="http://maps.google.com" target="_blank" rel="nofollow">15th Street, Miami, USA</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Contact Us
                    </p>
                    <p class="links_list-value">
                        <a href="mailto:support@email.com">Support@Email.com</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Phone
                    </p>
                    <p class="links_list-value">
                        <a href="tel:4785929899">(478)-592-9899</a>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>

web/templates/includes/scripts.html
{% load static %}
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/jquery-plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>