ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include("paypal.standard.ipn.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('',views.index,name='index'),
    path('categoria/<int:categoria_id>',views.productos_por_categoria,name='categoria'),
    path('marca/<int:marca_id>',views.productos_por_marca,name='marca'),
    path('busqueda',views.producto_por_nombre,name='busqueda'),
    path('producto/<int:producto_id>',views.producto_detalle,name='producto'),
    path('cart',views.carrito,name='carrito'),
    path('cart/add/<int:producto_id>',views.agregar_carrito,name='cart_add'),
    path('cart/del/<int:producto_id>',views.eliminar_producto_carrito,name='cart_del'),
    path('cart/clear',views.limpiar_carrito,name='cart_clear'),
    path('auth/register',views.crear_usuario,name='auth_register'),
    path('cuenta',views.cuenta_usuario,name='cuenta'),
    path('auth/login',views.login_usuario,name='auth_login'),
    path('auth/logout',views.logout_usuario,name='auth_logout'),
    path('cliente/act',views.actualizar_cliente,name='cliente_act'),
    path('pedido',views.pedido,name='pedido'),
    path('pedido/add',views.registrar_pedido,name='pedido_add'),
    path('pago',views.registro_pago,name='pago')
]

web/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    
    class Meta:
        db_table = 'tbl_categoria'
        
    def __str__(self):
        return self.nombre
    
class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    
    class Meta:
        db_table = 'tbl_marca'
        
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    marca = models.ForeignKey(Marca,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=250)
    descripcion = models.TextField(null=True)
    precio = models.DecimalField(max_digits=10,decimal_places=2)
    imagen = models.ImageField(upload_to='productos',blank=True)
    
    class Meta:
        db_table = 'tbl_producto'
        
    def __str__(self):
        return self.nombre

    
class ProductoImagen(models.Model):
    producto = models.ForeignKey(Producto,on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='galeria',null=True)
    
    class Meta:
        db_table = 'tbl_producto_imagen'
        verbose_name = 'Galeria de Fotos'
        verbose_name_plural = 'Galeria de Fotos'
        
    def __str__(self):
        return self.producto.nombre
    
from django.contrib.auth.models import User

class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.CASCADE)
    dni = models.CharField(max_length=20)
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()
    
    class Meta:
        db_table = 'tbl_cliente'
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
    
    def __str__(self):
        return self.dni
    
class Pedido(models.Model):
    
    ESTADO_CHOICES = (
        ('1','Solicitado'),
        ('2','Pagado')
    )
    
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    nro_pedido = models.CharField(max_length=20,null=True)
    direccion_envio = models.TextField(null=True)
    payer_id = models.CharField(max_length=200,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    estado = models.CharField(max_length=1,default='1',choices=ESTADO_CHOICES)
    
    class Meta:
        db_table = 'tbl_pedido'
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        
    def __str__(self):
        return self.nro_pedido
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)
    
    class Meta:
        db_table = 'tbl_pedido_detalle'
        verbose_name = 'Pedido Detalle'
        verbose_name_plural = 'Pedido Detalles'
        
    def __str__(self):
        return self.producto.nombre
    

web/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
<main id="main" class="site-main">
    <div class="cont maincont">
        <h1 class="maincont-ttl">Cart</h1>
        <ul class="b-crumbs">
            <li><a href="index.html">Home</a></li>
            <li>Cart</li>
        </ul><div class="page-styling">
        <div class="woocommerce prod-litems section-list">
            {%for key,value in request.session.cart.items %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        {% if value.imagen %}
                            <img src="{{value.imagen}}" alt="">
                        {% else %}
                            <img src="http://placehold.it/290x258" alt="">
                        {% endif %}
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{value.categoria}}</a>
                            </p>
                            <h3><a href="#">{{value.nombre}}</a></h3>
                        </div><!--
        No Space
        --><div class="prod-li-prices">
                        <div class="prod-li-price-wrap">
                            <p>Precio</p>
                            <p class="prod-li-price">${{value.precio}}</p>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{value.cantidad}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>SubTotal</p>
                            <p class="prod-li-total">${{value.subtotal}}</p>
                        </div>
                    </div><!--
No Space
--></div>
                    <div class="prod-li-info">
                        <div class="prod-li-rating-wrap">
                            <p data-rating="5" class="prod-li-rating">
                                <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                            </p>
                            <p class="prod-li-rating-count">12</p>
                        </div>
                        <p class="prod-li-add">
                            <a href="/cart/del/{{value.producto_id}}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i><span>Eliminar</span></a>
                        </p>
                        <p class="prod-li-compare">
                            <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                        </p>
                        <p class="prod-quickview">
                            <a href="#" class="hover-label quick-view"><i class="icon ion-plus"></i><span>Quick View</span></a>
                        </p>
                        <div class="prod-li-favorites">
                            <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                        </div>
                        <p class="prod-li-information">
                            <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                        </p>
                    </div>
                </div>
                <div class="page-styling prod-li-informations">
                    <p>{{value.descripcion | safe}}</p>
                </div>
            </article>
            {% endfor %}
        </div>
        <div class="cart-actions">
            <div class="coupon">
                <input type="text" placeholder="Coupon code">
                <input type="submit" class="button" value="Apply">
            </div>
            <div class="cart-collaterals">
                <a href="/cart/clear" class="checkout-button button">Limpiar</a>
                <a href="{% url 'web:pedido' %}" class="checkout-button button">Realizar Compra</a>
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">$510.00</p>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>
{% endblock %}

web/templates/cuenta.html
{% extends 'layout.html' %}
{% block content %}
<main id="main" class="site-main">
    <div class="cont maincont">
        <h1 class="maincont-ttl">Bienvenido  - {{user.username}}</h1>
        <ul class="b-crumbs">
            <li><a href="index.html">Home</a></li>
            <li>Cuenta de Usuario</li>
        </ul>
        <article class="page-cont">
        <div class="page-styling">
            
            <form method="post" action="{% url 'web:cliente_act' %}">
                {% csrf_token %}
                {{form}}
                <p class="auth-submit">
                    <input type="submit" value="Actualizar Datos">
                </p>
            </form>
        </div>
        </article>
    </div>
</main>
{% endblock %}

web/templates/gracias.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1>GRACIAS POR TU COMPRA</h1>
    <h2>Pedido  {{pedido.nro_pedido}} esta pagado</h2>
</div>
{% endblock %}

web/templates/index.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    {% include 'includes/catalogo/header.html' %}
    <!-- To make Sidebar "Not Sticky" just remove  id="section-list-withsb" -->
    <div class="section-wrap-withsb">
        {% include 'includes/catalogo/sidebar.html' %}        
        <div class="section-list-withsb" id="section-list-withsb">
        <div class="theiaStickySidebar">
            {% include 'includes/catalogo/productos.html' %}
        </div><!-- .theiaStickySidebar -->
    </div><!-- .section-list-withsb -->
    </div><!-- .section-wrap-withsb -->

</div>
{% endblock %}

web/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    {% include 'includes/meta.html' %}
</head>
<body>
<div id="page" class="site">
    {% include 'includes/navbar.html' %}
    {% include 'includes/header.html' %}
    <div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                {% block content %}
                {% endblock %}
            </main><!-- #main -->
        </div><!-- #primary -->
    </div><!-- #content -->
    {% include 'includes/footer.html' %}
    {% include 'includes/modals.html' %}
</div><!-- #page -->
{% include 'includes/scripts.html' %}
</body>
</html>

web/templates/login.html
{% extends 'layout.html' %}
{% block content %}
<main id="main" class="site-main">
    <div class="cont maincont">
        <h1 class="maincont-ttl">Registration / Login</h1>
        <ul class="b-crumbs">
            <li><a href="index.html">Home</a></li>
            <li>Registration & Login</li>
        </ul>
        <article class="page-cont">
            <div class="page-styling">
                <div class="auth-wrap">
                    <div class="auth-col">
                        <h2>Login</h2>
                        <form method="post" class="login" action="{% url 'web:auth_login' %}">
                            {% csrf_token %}
                            <input type="hidden" name="destino" value="{{destino}}"/>
                            <p>
                                <label for="username">E-mail <span class="required">*</span></label>
                                <input type="text" id="username" name="usuario">
                            </p>
                            <p>
                                <label for="password">Password <span class="required">*</span></label>
                                <input type="password" id="password" name="password">
                            </p>
                            <p class="auth-submit">
                                <input type="submit" value="Login">
                                <input type="checkbox" id="rememberme" value="forever">
                                <label for="rememberme">Remember me</label>
                            </p>
                            <p class="auth-lost_password">
                                <a href="#">Lost your password?</a>
                            </p>
                            <p>
                                <label for="alert-danger">{{mensaje}}</label>
                            </p>
                        </form>
                    </div>
                    <div class="auth-col">
                        <h2>Registro</h2>
                        <form method="post" class="register" action="{% url 'web:auth_register' %}">
                            {% csrf_token %}
                            <input type="hidden" name="destino" value="{{destino}}"/>
                            <p>
                                <label for="reg_email">Email <span class="required">*</span></label>
                                <input type="email" id="reg_email" name="usuario">
                            </p>
                            <p>
                                <label for="reg_password">Password <span class="required">*</span></label>
                                <input type="password" id="reg_password" name="password">
                            </p>
                            <p class="auth-submit">
                                <input type="submit" value="Registro Nuevo Usuario">
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </article>
    </div>
</main>
{% endblock %}

web/templates/pedido.html
{% extends 'layout.html' %}
{% block content %}
<main id="main" class="site-main">
<div class="cont maincont">
    <h1 class="maincont-ttl">REGISTRO DE PEDIDO</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>pedido</li>
    </ul>
    <form method="post" action="{% url 'web:pedido_add' %}" class="register">
        {% csrf_token %}
        <article class="page-cont">
            <div class="page-styling">
                <div class="auth-wrap">
                    <div class="auth-col">
                        <h2>Datos Personales</h2>
                        <p>
                            <label for="username">Nombres<span class="required">*</span></label>
                            {{form.nombre}}
                        </p>
                        <p>
                            <label for="username">Apellidos<span class="required">*</span></label>
                            {{form.apellidos}}
                        </p>
                        <p>
                            <label for="username">Dni<span class="required">*</span></label>
                            {{form.dni}}
                        </p>
                    </div>
                    <div class="auth-col">
                        <h2>Datos Envio</h2>
                        <p>
                            <label for="username">Email<span class="required">*</span></label>
                            {{form.email}}
                        </p>
                        <p>
                            <label for="username">Telefono<span class="required">*</span></label>
                            {{form.telefono}}
                        </p>
                        <p>
                            <label for="username">Dirección<span class="required">*</span></label>
                            {{form.direccion}}
                        </p>
                    </div>
                </div>
            </div>
        </article>
        <article class="page-cont">
            <div class="page-styling">
                <h2>Confirmación de Productos</h2>
                <div class="woocommerce prod-litems section-list">
                    {% for key,value in request.session.cart.items %}
                    <article class="prod-li sectls">
                        <div class="prod-li-inner">
                            <a href="#" class="prod-li-img">
                                <img src="{{ value.imagen }}" alt="">
                            </a>
                            <div class="prod-li-cont">
                                <div class="prod-li-ttl-wrap">
                                    <p>
                                        <a href="#">{{value.categoria}}</a>
                                    </p>
                                    <h3><a href="product.html">{{ value.nombre }}</a></h3>
                                </div>
                                <div class="prod-li-prices">
                                    <div class="prod-li-price-wrap">
                                        <p>Precio</p>
                                        <p class="prod-li-price">${{value.precio}}</p>
                                    </div>
                                </div>
                                <div class="prod-li-qnt-wrap">
                                    <p class="qnt-wrap prod-li-qnt">
                                        <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                        <input type="text" value="{{value.cantidad}}">
                                        <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                    </p>
                                </div>
                                <div class="prod-li-total-wrap">
                                    <p>Total</p>
                                    <p class="prod-li-total">${{value.subtotal}}</p>
                                </div>
                            </div>
                        </div>
                    </article>
                    {% endfor %}
            </div>
            <div class="cart-actions">
                    <div class="cart-collaterals">
                        <div class="order-total">
                            <p class="cart-totals-ttl">Total</p>
                            <p class="cart-totals-val">$100</p>
                        </div>
                    </div>
            </div>
            </div>
        </article>
        <article class="page-cont">
            <div class="page-styling">
                <div class="auth-wrap">
                    <div class="auth-col">
                        <p class="auth-submit">
                            <input type="submit" value="Confirmar Pedido">
                        </p>
                </div>
            </div>
        </article>
    </form>
</div>
</main>
{% endblock %}

web/templates/pedido_confirmado.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1>PEDIDO CONFIRMADO</h1>
    <h2>codigo : {{pedido.nro_pedido}}</h2>
    {{form.render}}
</div>
{% endblock %}

web/templates/producto.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <div class="cont maincont">
        <ul class="b-crumbs">
            <li><a href="index.html">Home</a></li>
            <li><a href="catalog-gallery.html">Catalog</a></li>
            <li>Product</li>
        </ul>            
        <article>
            <div class="prod">
                <div class="prod-slider-wrap prod-slider-shown">
                    <div class="flexslider prod-slider" id="prod-slider">
                        <ul class="slides">
                            {% for galeria in producto.productoimagen_set.all %}
                            <li>
                                <a data-fancybox-group="prod" class="fancy-img" href="{{galeria.imagen.url}}">
                                    <img src="{{galeria.imagen.url}}" alt="">
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                        <div class="prod-slider-count"><p><span class="count-cur">1</span> / <span class="count-all">2</span></p><p class="hover-label prod-slider-zoom"><i class="icon ion-search"></i><span>Zoom In</span></p></div>
                    </div>
                    <div class="flexslider prod-thumbs" id="prod-thumbs">
                        <ul class="slides">
                            {% for galeria in producto.productoimagen_set.all %}
                                <li>
                                    <img src="{{galeria.imagen.url}}" alt="">
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="prod-cont">
                    <div class="prod-rating-wrap">
                        <p data-rating="4" class="prod-rating">
                            <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i>
                            <i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                        </p>
                        <p class="prod-rating-count">7</p>
                    </div>
                    <p class="prod-categs"><a href="#">{{producto.categoria.nombre}}</a>, <a href="#">{{producto.marca.nombre}}</a></p>
                    <h1>{{producto.nombre}}</h1>
                    <div class="variations_form cart">
                        <p class="prod-price">${{producto.precio}}</p>
                        <p class="prod-excerpt">
                            {{producto.descripcion | safe }}
                        </p>
                        <form action="{% url 'web:cart_add' producto.id %}" method="post">
                        {% csrf_token %}
                        <div class="prod-add">
                            <p class="qnt-wrap prod-li-qnt">
                                
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="1" name="cantidad">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            
                            </p>
                            <button type="submit" class="button"><i class="icon ion-android-cart"></i> Add to cart</button>
                            
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </article>
    </div>
</div>
{% endblock %}