ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include("paypal.standard.ipn.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('',views.index,name='index'),
    path('categoria/<int:categoria_id>',views.productos_por_categoria,name='categoria'),
    path('marca/<int:marca_id>',views.productos_por_marca,name='marca'),
    path('busqueda',views.producto_por_nombre,name='busqueda'),
    path('producto/<int:producto_id>',views.producto_detalle,name='producto'),
    path('cart',views.carrito,name='carrito'),
    path('cart/add/<int:producto_id>',views.agregar_carrito,name='cart_add'),
    path('cart/del/<int:producto_id>',views.eliminar_producto_carrito,name='cart_del'),
    path('cart/clear',views.limpiar_carrito,name='cart_clear'),
    path('auth/register',views.crear_usuario,name='auth_register'),
    path('cuenta',views.cuenta_usuario,name='cuenta'),
    path('auth/login',views.login_usuario,name='auth_login'),
    path('auth/logout',views.logout_usuario,name='auth_logout'),
    path('cliente/act',views.actualizar_cliente,name='cliente_act'),
    path('pedido',views.pedido,name='pedido'),
    path('pedido/add',views.registrar_pedido,name='pedido_add'),
    path('pago',views.registro_pago,name='pago')
]

web/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    
    class Meta:
        db_table = 'tbl_categoria'
        
    def __str__(self):
        return self.nombre
    
class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    
    class Meta:
        db_table = 'tbl_marca'
        
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    marca = models.ForeignKey(Marca,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=250)
    descripcion = models.TextField(null=True)
    precio = models.DecimalField(max_digits=10,decimal_places=2)
    imagen = models.ImageField(upload_to='productos',blank=True)
    
    class Meta:
        db_table = 'tbl_producto'
        
    def __str__(self):
        return self.nombre

    
class ProductoImagen(models.Model):
    producto = models.ForeignKey(Producto,on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='galeria',null=True)
    
    class Meta:
        db_table = 'tbl_producto_imagen'
        verbose_name = 'Galeria de Fotos'
        verbose_name_plural = 'Galeria de Fotos'
        
    def __str__(self):
        return self.producto.nombre
    
from django.contrib.auth.models import User

class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.CASCADE)
    dni = models.CharField(max_length=20)
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()
    
    class Meta:
        db_table = 'tbl_cliente'
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
    
    def __str__(self):
        return self.dni
    
class Pedido(models.Model):
    
    ESTADO_CHOICES = (
        ('1','Solicitado'),
        ('2','Pagado')
    )
    
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    nro_pedido = models.CharField(max_length=20,null=True)
    direccion_envio = models.TextField(null=True)
    payer_id = models.CharField(max_length=200,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    estado = models.CharField(max_length=1,default='1',choices=ESTADO_CHOICES)
    
    class Meta:
        db_table = 'tbl_pedido'
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        
    def __str__(self):
        return self.nro_pedido
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)
    
    class Meta:
        db_table = 'tbl_pedido_detalle'
        verbose_name = 'Pedido Detalle'
        verbose_name_plural = 'Pedido Detalles'
        
    def __str__(self):
        return self.producto.nombre
    

web/templates/includes/catalogo/header.html
<div class="section-top">
    <h1 class="maincont-ttl">Shop</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Catalog - Gallery</li>
    </ul>
    <div class="section-top-sort">
        <div class="section-view">
            <p>View</p>
            <div class="dropdown-wrap">
                <p class="dropdown-title section-view-ttl">Gallery</p>
                <ul class="dropdown-list">
                    <li>
                        <a href="catalog-list.html">List</a>
                    </li>
                    <li class="active">
                        <a href="catalog-gallery.html">Gallery</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="section-sort">
            <p>Sort</p>
            <div class="dropdown-wrap">
                <p class="dropdown-title section-sort-ttl">Newness</p>
                <ul class="dropdown-list">
                    <li>
                        <a href="#">Popularity</a>
                    </li>
                    <li>
                        <a href="#">Average rating</a>
                    </li>
                    <li class="active">
                        <a href="#">Newness</a>
                    </li>
                    <li>
                        <a href="#">Price: low to high</a>
                    </li>
                    <li>
                        <a href="#">Price: high to low</a>
                    </li>
                </ul>
            </div>
        </div>
        <form method="post" class="products-per-page">
            <p>Per Page</p>
            <select>
                <option value="12" selected="selected">12</option>
                <option value="24">24</option>
                <option value="48">48</option>
                <option value="-1">All</option>
            </select>
        </form>
    </div>
</div>

web/templates/includes/catalogo/productos.html
<div class="row prod-items prod-items-2">
    {% for producto in productos %}
        <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
            <div class="sectgl prod-i">
                <div class="prod-i-top">
                    <a class="prod-i-img" href="{% url 'web:producto' producto.id %}">
                        {% if producto.imagen %}
                            <img src="{{producto.imagen.url}}" alt="">
                        {% else %}
                            <img src="http://placehold.it/290x258" alt="">
                        {% endif %}
                    </a>
                    <div class="prod-i-actions">
                        <div class="prod-i-actions-in">
                            <p class="prod-i-cart">
                                <a href="/cart/add/{{producto.id}}" class="hover-label prod-addbtn">
                                    <i class="icon ion-android-cart"></i>
                                    <span>Add to Cart</span>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="prod-i-bot">
                    <div class="prod-i-info">
                        <p class="prod-i-price">${{producto.precio}}</p>
                        <p class="prod-i-categ"><a href="{% url 'web:categoria' producto.categoria.id %}">{{producto.categoria}}</a></p>
                    </div>
                    <h3 class="prod-i-ttl"><a href="{% url 'web:producto' producto.id %}">{{producto.nombre}}</a></h3>
                </div>
            </div>
        </article>
    {% endfor %}
</div>
<ul class="page-numbers">
    <li><span class="page-numbers current">1</span></li>
    <li><a class="page-numbers" href="#">2</a></li>
    <li><a class="page-numbers" href="#">3</a></li>
    <li><a class="page-numbers" href="#">4</a></li>
    <li><a class="next page-numbers" href="#"><i class="fa fa-angle-right"></i></a></li>
</ul>

web/templates/includes/catalogo/sidebar.html
<aside class="blog-sb-widgets section-sb" id="section-sb">
    <div class="theiaStickySidebar">
        <p class="section-filter-toggle filter_hidden">
            <a href="#" id="section-filter-toggle-btn">Filtrar</a>
        </p>
        <div class="section-filter">
            <div class="section-filter">
                <div class="blog-sb-widget multishopcategories_widget">
                    <h3 class="widgettitle">Categorias</h3>
                    <div class="section-sb-current">
                        <ul class="section-sb-list">
                            {% for categoria in categorias %}
                            <li>
                                <a href="{% url 'web:categoria' categoria.id %}">
                                    <span class="section-sb-label">{{categoria.nombre}} 
                                    <span class="count">{{categoria.producto_set.all.count}}</span></span></a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="blog-sb-widget multishopbrands_widget">
                    <h3 class="widgettitle">Marcas</h3>
                    <ul class="brands-list-sb">
                        {% for marca in marcas %}
                        <li>
                            <a href="{% url 'web:marca' marca.id %}">{{marca.nombre}} 
                                <span class="count">{{marca.producto_set.all.count}}</span></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</aside>